import {
  Anvil,
  BedDouble,
  Bike,
  BookOpen,
  Bubbles,
  Building2,
  CalendarDays,
  Camera,
  Candy,
  CarFront,
  Coffee,
  Cpu,
  Croissant,
  Dog,
  Droplets,
  Dumbbell,
  Flower2,
  Footprints,
  Gem,
  Gift,
  GraduationCap,
  Hammer,
  Hospital,
  House,
  Lamp,
  MapPin,
  PawPrint,
  Pencil,
  PersonStanding,
  Pill,
  Plane,
  Printer,
  Ruler,
  School,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  SmilePlus,
  Smartphone,
  Sofa,
  Sparkles,
  Stethoscope,
  Store,
  UtensilsCrossed,
  WashingMachine,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const businessIcons = {
  basket: ShoppingBasket,
  beam: Anvil,
  building: Building2,
  bag: ShoppingBag,
  shirt: Shirt,
  cleaning: Bubbles,
  utensils: UtensilsCrossed,
  cup: Coffee,
  bread: Croissant,
  candy: Candy,
  bed: BedDouble,
  scissors: Scissors,
  flower: Flower2,
  spa: Sparkles,
  hanger: Store,
  gem: Gem,
  shoe: Footprints,
  hammer: Hammer,
  bolt: Zap,
  phone: Smartphone,
  chip: Cpu,
  sofa: Sofa,
  lamp: Lamp,
  medical: Pill,
  stethoscope: Stethoscope,
  tooth: SmilePlus,
  hospital: Hospital,
  dumbbell: Dumbbell,
  yoga: PersonStanding,
  school: School,
  book: BookOpen,
  coaching: GraduationCap,
  pencil: Pencil,
  gift: Gift,
  paw: PawPrint,
  veterinary: Dog,
  car: CarFront,
  wrench: Wrench,
  bicycle: Bike,
  droplet: Droplets,
  house: House,
  plane: Plane,
  calendar: CalendarDays,
  camera: Camera,
  washer: WashingMachine,
  printer: Printer,
  tailor: Ruler,
  pin: MapPin,
} as const satisfies Record<string, LucideIcon>;

export type BusinessIconName = keyof typeof businessIcons;

export function BusinessAudienceIcon({ name }: { name: BusinessIconName }) {
  const Icon = businessIcons[name];

  return <Icon aria-hidden="true" focusable="false" strokeWidth={1.8} />;
}
