-- AMENDMENT-027/028/029/030 — admin MFA and team, user activity log, payment control (refunds,
-- invoices, reminders), abuse controls. Generated by drizzle-kit from the schema; the only hand
-- edit is the removal of a drop/re-add of subscriptions_entitlement_granted_by_users_id_fk that a
-- stale snapshot inferred (the constraint is already ON DELETE set null since 0005).
CREATE TABLE "mfa_recovery_codes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"code_hash" char(64) NOT NULL,
	"used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "mfa_recovery_codes_code_hash_unique" UNIQUE("code_hash")
);
--> statement-breakpoint
CREATE TABLE "invoice_sequences" (
	"series" varchar(20) PRIMARY KEY NOT NULL,
	"next_value" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payment_refunds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"payment_id" uuid NOT NULL,
	"provider_refund_id" varchar(120),
	"amount_paise" integer NOT NULL,
	"status" varchar(16) DEFAULT 'REQUESTED' NOT NULL,
	"reason" varchar(1000),
	"requested_by" uuid,
	"error" varchar(500),
	"raw_reference" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"processed_at" timestamp with time zone,
	CONSTRAINT "payment_refunds_provider_refund_id_unique" UNIQUE("provider_refund_id"),
	CONSTRAINT "ck_refund_amount_positive" CHECK (amount_paise > 0),
	CONSTRAINT "ck_refund_status" CHECK (status IN ('REQUESTED', 'PENDING', 'PROCESSED', 'FAILED'))
);
--> statement-breakpoint
CREATE TABLE "subscription_reminders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"subscription_id" uuid NOT NULL,
	"business_id" uuid NOT NULL,
	"kind" varchar(12) NOT NULL,
	"period_expires_at" timestamp with time zone NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"sent_at" timestamp with time zone,
	"skipped_at" timestamp with time zone,
	"last_error" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ck_reminder_kind" CHECK (kind IN ('T30', 'T7', 'T1', 'EXPIRED'))
);
--> statement-breakpoint
CREATE TABLE "user_activity_logs" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "user_activity_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid,
	"business_id" uuid,
	"session_id" uuid,
	"action" varchar(80) NOT NULL,
	"outcome" varchar(16) DEFAULT 'SUCCESS' NOT NULL,
	"target_type" varchar(80),
	"target_id" varchar(120),
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"ip_hash" char(64),
	"user_agent" varchar(400),
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ck_activity_outcome" CHECK (outcome IN ('SUCCESS', 'FAILURE', 'DENIED'))
);
--> statement-breakpoint
ALTER TABLE "admin_audit_logs" ALTER COLUMN "actor_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "mfa_verified_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "user_invites" ADD COLUMN "role" "user_role" DEFAULT 'BUSINESS_OWNER' NOT NULL;--> statement-breakpoint
ALTER TABLE "user_invites" ADD COLUMN "full_name" varchar(120);--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "mfa_last_used_step" bigint;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "disabled_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "disabled_reason" varchar(500);--> statement-breakpoint
ALTER TABLE "businesses" ADD COLUMN "billing_legal_name" varchar(200);--> statement-breakpoint
ALTER TABLE "businesses" ADD COLUMN "gstin" varchar(15);--> statement-breakpoint
ALTER TABLE "businesses" ADD COLUMN "billing_state_code" char(2);--> statement-breakpoint
ALTER TABLE "businesses" ADD COLUMN "billing_address" varchar(500);--> statement-breakpoint
ALTER TABLE "businesses" ADD COLUMN "ai_suspended_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "businesses" ADD COLUMN "ai_suspended_reason" varchar(500);--> statement-breakpoint
ALTER TABLE "businesses" ADD COLUMN "ai_throttle_until" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "businesses" ADD COLUMN "ai_throttle_per_hour" integer;--> statement-breakpoint
ALTER TABLE "payment_webhook_events" ADD COLUMN "payment_id" uuid;--> statement-breakpoint
ALTER TABLE "payment_webhook_events" ADD COLUMN "outcome" varchar(16);--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "refunded_paise" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "refunded_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "failure_reason" varchar(500);--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "invoice_number" varchar(40);--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "invoice_issued_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "tax_breakdown" jsonb;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "seller_snapshot" jsonb;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "buyer_snapshot" jsonb;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "receipt_emailed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "admin_audit_logs" ADD COLUMN "actor_type" varchar(16) DEFAULT 'ADMIN' NOT NULL;--> statement-breakpoint
ALTER TABLE "mfa_recovery_codes" ADD CONSTRAINT "mfa_recovery_codes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_refunds" ADD CONSTRAINT "payment_refunds_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_refunds" ADD CONSTRAINT "payment_refunds_requested_by_users_id_fk" FOREIGN KEY ("requested_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subscription_reminders" ADD CONSTRAINT "subscription_reminders_subscription_id_subscriptions_id_fk" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscriptions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subscription_reminders" ADD CONSTRAINT "subscription_reminders_business_id_businesses_id_fk" FOREIGN KEY ("business_id") REFERENCES "public"."businesses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_activity_logs" ADD CONSTRAINT "user_activity_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_activity_logs" ADD CONSTRAINT "user_activity_logs_business_id_businesses_id_fk" FOREIGN KEY ("business_id") REFERENCES "public"."businesses"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_mfa_recovery_user" ON "mfa_recovery_codes" USING btree ("user_id") WHERE used_at IS NULL;--> statement-breakpoint
CREATE INDEX "idx_payment_refunds_payment" ON "payment_refunds" USING btree ("payment_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "uq_reminder_once" ON "subscription_reminders" USING btree ("subscription_id","period_expires_at","kind");--> statement-breakpoint
CREATE INDEX "idx_reminders_pending" ON "subscription_reminders" USING btree ("sent_at") WHERE sent_at IS NULL AND skipped_at IS NULL;--> statement-breakpoint
CREATE INDEX "idx_activity_business_time" ON "user_activity_logs" USING btree ("business_id","occurred_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_activity_user_time" ON "user_activity_logs" USING btree ("user_id","occurred_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_activity_action_time" ON "user_activity_logs" USING btree ("action","occurred_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_activity_time" ON "user_activity_logs" USING btree ("occurred_at" DESC NULLS LAST);--> statement-breakpoint
ALTER TABLE "payment_webhook_events" ADD CONSTRAINT "payment_webhook_events_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_webhook_events_time" ON "payment_webhook_events" USING btree ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_payments_status_time" ON "payments" USING btree ("status","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_payments_provider_payment" ON "payments" USING btree ("provider_payment_id");--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_invoice_number_unique" UNIQUE("invoice_number");--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "ck_refund_within_amount" CHECK (refunded_paise >= 0 AND refunded_paise <= amount_paise);--> statement-breakpoint
ALTER TABLE "admin_audit_logs" ADD CONSTRAINT "ck_audit_actor_present" CHECK (actor_type = 'SYSTEM' OR actor_user_id IS NOT NULL);